### ISSUE TITLE
PH-tree C++ version

### ISSUE THREAD

**Issue by andredemori** [tzaeschke/phtree#15]
Hi, i am trying to compile PH-tree C++ version for implement in another project. I'm trying to run the project on Clion. Do you have the CMakeList file? How you compile that? I'm trying to compile just the main file on terminal, but it's not working. 

Best regards.

**Comment by tzaeschke** [comment]
I assume you mean this version: https://github.com/mcxme/phtree ?
It is maintained by someone else, and I do not have tried compiling it yet.

How urgently do you need the PH-tree? I am currently working on my own C++ version, but it will be a few weeks at least before it I can release it.

**Comment by andredemori** [comment]
Thanks for the answer. I will wait for the release and meanwhile I will index the data with other structures. I would like to test with PH-tree soon because the results obtained with the Java version were very good. Thankful.

**Comment by tzaeschke** [comment]
This took a bit longer than I thought, but here it is:
[https://github.com/improbable-eng/phtree-cpp](https://github.com/improbable-eng/phtree-cpp)

**Comment by andredemori** [comment]
Thanks for the mail!

________________________________
De: Tilmann <notifications@github.com>
Enviado: sexta-feira, 3 de julho de 2020 13:52
Para: tzaeschke/phtree <phtree@noreply.github.com>
Cc: andredemori <andre_demori@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [tzaeschke/phtree] PH-tree C++ version (#15)


This took a bit longer than I thought, but here it is:
https://github.com/improbable-eng/phtree-cpp
