### ISSUE TITLE
How PH-tree works with negative values?

### ISSUE THREAD

**Issue by andredemori** [tzaeschke/phtree#8]
Hello, another question I am studying that I did not find in the article is how binary conversion occurs on PH-tree with negative numbers. In the case of my project, I work with spatial positions, being right ascension and declination. Declination can have negative values. Can this affect something in the insertion and search in the PH-tree or does it come naturally with bit insertion?

Thank you in advance.

**Comment by tzaeschke** [comment]
Negative values are handled normally just as rational numbers. I guess when using angular coordinates, you have to look out for +180 not being a neighbor of (or the same as) -180.

You can find a brief discussion in section 3.3 in the [original paper](https://github.com/tzaeschke/phtree/blob/master/PH-Tree-v1.1-2014-06-28.pdf).
